language: java
jdk: openjdk11
deploy:
  provider: heroku
  api_key:
    secure: rZGIMclmdn1xvMvGxZuk8YGV4mtkch7ZUzEyTo3L2ZYbvSuC0yzm8tZtV9eIokjcrP3adQQ+hJp6lvDB9biDsdqQ+W2P6OjFYLvjlHqL04yF1/RbeGgUgVrSjyZm7iLPQAJeffeUQ3pqOyy/oQGne3XLnt+6STVu+A+x+XvO5Rx6Q6kjfXmA67EnCKp01NjkYbsgei+IQnT6OjFf6HBPoYbMHOzJBwdtBU7noh8qa2sH1pPzGB8V/NEU21XEFshgcszXhA6s81fDvXiHGkzrxSnbZPrZ89MQcr8aK+cMow2/ZMZ8MAmQ7qKw6sQSXFrzocnsRZyZ5mFC9m9m0VuiWFYLZELDPNFulbE4I3knhY36ZQpzZ+KUhS6vNT1MAy2/6eWGZlKiN8+ed1kAU2f2zDTBXKH5oLqVCQTsarydAz3rUQxFraZzEkBnhuKltED7+B35EDoojaxjwb4+93gRTYNgTzx4EYAZBDxTqNmXi4V6vUCAwZDCcQMPUTI2/bhJtHxZD1A/vyikV0+ocBYk2qlsEMBY8trEy/PDb6wCcfpMR8gizlf4I49wn+DmNqlj2JEyjUAqoNE6jVwxEtxvaHHq24XwNUiIq5h8JQ1/r9nTjMMeROIUTtWkaxw45Cu2bhWUvqnEN3jfkBqRvkr9IRirqj7fhSmuIOVULPYS/O0=
  app: app4masha
