language: java
jdk: openjdk11
deploy:
  provider: heroku
  api_key:
    secure: UKU1KierHvEAJwlgBCGiPgec1kIAufSbHGhxp30wYZ8SCKjtF2ySlxHHTbDv77r4kz+ZfoqfeaaXZQLxq7tSRR5fQ+GTGQZAhWKgFv+bliZFycQRzZYCXOFdL6MJsCRlpcKqPYgDJTJfv5Um7NVvsYSfmqHlmYRWTtb6pqWDDWGHUxiSI9IxeGgMs4Wb/vbHlxaF/jEpSg8naeSvetj6TLXjG35bwMC1nXx9e/oIZAcAGMKvfBLh+3nKvOkfZXu9nBLUU8koberHY+p9Jdo6YJNPOHDxjL9BPfVVP5NsXXaLKeylYXcFsMO6hj4uTPHuFzXnRpLqkU6fIqHD0zE0vmswFvSXNHUGuDVn8aKxWmw2h0fxGvbWRb5VlctPys+31hah38tdXVA1XdiawwSoTLPKowcvV8ItYs1jFdVG1k2NSThECshEFKlv2NtDd4gbi5XhEa9yQQSpnO2Wf9cnTR0vOrfH3ezEJgYc1E7zZu/O7iinwebR5gx61cYw4dzs/rg28zzsbJR6KCObgyWJ14EfxamsFJrkmkZ5wUZZ+Fp6WWs3B1D4e/C8SPZA1Yt7SPE8qj5ftd/M3ohwypc1q5iVq+3cSf/BBYTj86MZaeIovO25dLR1EvCdOVdz8XRZVx8HZ97KDPappsayN0PQP70HfU/zN54SYsVlX2RyM/w=
  app: app4masha
