language: java
jdk: openjdk11
deploy:
  provider: heroku
  api_key:
    secure: R2hsQXqJthjbIBEiSjVppf6OfFxlKvvPGXYCuDxrXVJTZOd/RptwwMfJ0ejawYsYqCN7PduXxgw5ZDji0Ol5CTnIIxaGQJEu6DQkaM1uqdO2ZVzr2zdSy+mW4soyo39Tc/pGK7Ke07gIwtD4siBvzVSFDY1/ygB/gQH80dahY7ZQhPgTr0VB9jxQCiC1bpyJcktB9IGnULB5ciVAWaZwubd8CgCmELrn0IV21Nxqjqb1FjLcIXogWGaOFQvqjqRyapW4XtWCScKVKQozgYMgSphtBDxP8EXp/4PteW/Ondh4AG/rnf26snA6hI8FmcdEEgyQ0C0I6ctbE67heYKqEkfxUCFA4+wEXRDF2zPOOhwdar1gkzUagF7JTlas7VQU4RVfvXYTYbcdwGuoHCWco8b68m2YWAX+k5FYMhlp6ISdrwBV9gX94tO+Zzt/EhbanA3CsGKSv1uw44bzJ46fmsdb6O1t0F9f8eAane7JYplKiOKyeryPdU18zftFIC260V+jc5gGUA+zYT5W0B0mmLVSm4vrijiV/QmZgiQmcE7xR5Nf5XSiK4M6+3aC9j+Fq5GEEkT9uOi4qDVO2N9ELaRpBHjMI+2OodtX4d6fI/cXP+ZWpukNwygQGTayc+TuVM6TlulO5+aIW3DgO789JPvSZrxYxO2yGcx0zmQ4O3g=
  app: app4masha
  